# Generated by Django 4.0.5 on 2022-06-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usertoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
