# Generated by Django 4.0.5 on 2022-06-25 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_task_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Item',
        ),
    ]
